Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,12 +16,14 @@ discover_plugins:
     - apt-get update && apt-get install -y curl jq
     - |
       # Get plugins and filter for those that have Linux AMD64 support
-      curl -s "$GRAFANA_API_URL" |jq -r '.items[]? | select (.packages[]?.packageName == "linux-amd64" or .packages[]?.packageName == "any") | .slug' > plugins.txt
+      curl -s "$GRAFANA_API_URL" |jq -r '.items[]? | select (.packages[]?.packageName == "linux-amd64") | .slug' > plugins-linux-amd64.txt
+      curl -s "$GRAFANA_API_URL" |jq -r '.items[]? | select (.packages[]?.packageName == "any") | .slug' > plugins-any.txt
     - |
       echo "Found $(wc -l < plugins.txt) Linux AMD64 compatible plugins"
   artifacts:
     paths:
-      - plugins.txt
+      - plugins-linux-amd64.txt
+      - plugins-any.txt
     expire_in: 1 day
 
 download_plugins:
@@ -36,19 +38,30 @@ download_plugins:
       echo "Creating directory: $PLUGINS_DIR"
       mkdir -p $PLUGINS_DIR
     - |
-      while IFS= read -r plugin; do
+      for plugin in $(cat plugins-linux-amd64.txt); do
         echo "Downloading plugin: $plugin"
-        # Get the latest version info for Linux AMD64
         version_info=$(curl -s "$GRAFANA_API_URL/$plugin" | jq -r '.items[]? | select (.packages[]?.packageName == "linux-amd64" or .packages[]?.packageName == "any")  | .version')
+
         if [ ! -z "$version_info" ]; then
-          version=$(echo "$version_info" | jq -r '.version')
-          echo "Latest Linux AMD64 version: $version"
-          download_url="$GRAFANA_API_URL/$plugin/versions/$version/download?os=linux&arch=amd64"
-          curl -L -o "$PLUGINS_DIR/$plugin.zip" "$download_url" || echo "Failed to download $plugin"
+          # version=$(echo "$version_info" | jq -r '.version')
+          # curl -L -o "$PLUGINS_DIR/$plugin.zip" "$download_url" || echo "Failed to download $plugin"
         else
-          echo "Skipping $plugin - No Linux AMD64 version available"
+          echo "Skipping $plugin - No version available"
         fi
-      done < plugins.txt
+      done
+        # curl -L -o "$PLUGINS_DIR/$plugin.zip" "$download_url" || echo "Failed to download $plugin"        
+        # Get the latest version info for Linux AMD64
+        
+        # if [ ! -z "$version_info" ]; then
+          # version=$(echo "$version_info" | jq -r '.version')
+          # echo "Latest Linux AMD64 version: $version"
+          # download_url="$GRAFANA_API_URL/$plugin/versions/$version/download?os=linux&arch=amd64"
+          # echo "#Download Url: {download_url}"
+          # curl -L -o "$PLUGINS_DIR/$plugin.zip" "$download_url" || echo "Failed to download $plugin"
+        # else
+          # echo "Skipping $plugin - No Linux AMD64 version available"
+        # fi
+      # done < plugins.txt
     - echo "PLUGINS_DIR=$PLUGINS_DIR" >> variables.env
   artifacts:
     paths:
